[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Light"

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 130
lines = 45
